### ISSUE TITLE
Printing multiple copies of a label results in an error

### ISSUE THREAD

**Issue by saschaludwig** [inventree/inventree-brother-plugin#42]
This error occurs, whenever I try printing multiple (for example 10) copies of a label.
Only 5 labels get printed. Then the error occurs:

```
Traceback (most recent call last):

File "/home/inventree/src/backend/InvenTree/plugin/base/label/label.py", line 36, in print_label
plugin.print_label(**kwargs)

File "/usr/local/lib/python3.11/site-packages/inventree_brother/brother_plugin.py", line 232, in print_label
send(

File "/usr/local/lib/python3.11/site-packages/brother_ql/backends/helpers.py", line 57, in send
printer = BrotherQLBackend(printer_identifier)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/usr/local/lib/python3.11/site-packages/brother_ql/backends/network.py", line 50, in __init__
self.s.connect((host, port))

ConnectionRefusedError: [Errno 111] Connection refused
```

I'm using a QL-720NW, connected via LAN.
It looks like the printer won't accept connections while it is still printing, or some other race condition.
After the error occurs, I can print normally.

**Comment by SchrodingersGat** [comment]
@saschaludwig sorry for the delayed response on this one - the solution here would be to send all the copies as a single job to the printer - rather than sending each copy as a separate job.

**Comment by SchrodingersGat** [comment]
> Is there something I can configure or change?

No, at this stage it's an issue with the implementation. Each printing job is sent separately but they should be collated before sending to the printer. I guess because this is not happening the printer is being overwhelmed

**Comment by SchrodingersGat** [comment]
> Or is this something that has to be implemented by a plugin developer?

I do not have access to one of these printers currently - would you have any ability to test some code changes on your end?

**Comment by saschaludwig** [comment]
> I do not have access to one of these printers currently - would you have any ability to test some code changes on your end?
Yes, I would definitely help to try code changes.
